# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

infHS_FB <- function(B, bn, y, X, Z_list, M, hyp_sigma, a_k, b_k, s0 = 1, ping = 1000L) {
    .Call(`_infHS_infHS_FB`, B, bn, y, X, Z_list, M, hyp_sigma, a_k, b_k, s0, ping)
}

infHS_VB <- function(y, X, Z_list, M, hyp_sigma, a_k, b_k, s0 = 1, bmax = 1000L, eps = 1e-03, ping = 100L) {
    .Call(`_infHS_infHS_VB`, y, X, Z_list, M, hyp_sigma, a_k, b_k, s0, bmax, eps, ping)
}

infHS_VB_probit <- function(y, X, Z_list, M, a_k, b_k, s0 = 1, bmax = 1000L, eps = 1e-03, ping = 100L) {
    .Call(`_infHS_infHS_VB_probit`, y, X, Z_list, M, a_k, b_k, s0, bmax, eps, ping)
}

rg3p <- function(a, b, c) {
    .Call(`_infHS_rg3p`, a, b, c)
}

solve_quartic <- function(coefficients) {
    .Call(`_infHS_solve_quartic`, coefficients)
}

solve_quartic2 <- function(a1, a2, a3) {
    .Call(`_infHS_solve_quartic2`, a1, a2, a3)
}

rmvnorm_b <- function(X, y, d, sigma2) {
    .Call(`_infHS_rmvnorm_b`, X, y, d, sigma2)
}

rlambda <- function(d, a, b) {
    .Call(`_infHS_rlambda`, d, a, b)
}

log_kf <- function(d, a, b) {
    .Call(`_infHS_log_kf`, d, a, b)
}

m_e1 <- function(d, a, b, lkf) {
    .Call(`_infHS_m_e1`, d, a, b, lkf)
}

m_e2 <- function(d, a, b, lkf) {
    .Call(`_infHS_m_e2`, d, a, b, lkf)
}

m_e3 <- function(d, a, b, lkf) {
    .Call(`_infHS_m_e3`, d, a, b, lkf)
}

